// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfCezobmnG1bNJxJX8efc4mCcSlewKcvc',
    appId: '1:289265862580:web:ab15571b2d565f1500d4e1',
    messagingSenderId: '289265862580',
    projectId: 'ts-training-demo-ca',
    authDomain: 'ts-training-demo-ca.firebaseapp.com',
    storageBucket: 'ts-training-demo-ca.firebasestorage.app',
    measurementId: 'G-MYLVZYW6SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUAo7IObVKjSIJN2qVHlaelwRQEBEOX-8',
    appId: '1:289265862580:android:3d99d79b20c0b8c200d4e1',
    messagingSenderId: '289265862580',
    projectId: 'ts-training-demo-ca',
    storageBucket: 'ts-training-demo-ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVBCvjSbOVwCQKIE9WsyaWHhxYDv0zr5M',
    appId: '1:289265862580:ios:3dc808932cc4058f00d4e1',
    messagingSenderId: '289265862580',
    projectId: 'ts-training-demo-ca',
    storageBucket: 'ts-training-demo-ca.firebasestorage.app',
    iosBundleId: 'com.example.tsTrainingDemoCa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVBCvjSbOVwCQKIE9WsyaWHhxYDv0zr5M',
    appId: '1:289265862580:ios:3dc808932cc4058f00d4e1',
    messagingSenderId: '289265862580',
    projectId: 'ts-training-demo-ca',
    storageBucket: 'ts-training-demo-ca.firebasestorage.app',
    iosBundleId: 'com.example.tsTrainingDemoCa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfCezobmnG1bNJxJX8efc4mCcSlewKcvc',
    appId: '1:289265862580:web:0a3b18ab2e124b8e00d4e1',
    messagingSenderId: '289265862580',
    projectId: 'ts-training-demo-ca',
    authDomain: 'ts-training-demo-ca.firebaseapp.com',
    storageBucket: 'ts-training-demo-ca.firebasestorage.app',
    measurementId: 'G-WCGDKTET6M',
  );
}
